/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const afterUpdate: typeof import('svelte').afterUpdate
  const beforeUpdate: typeof import('svelte').beforeUpdate
  const createEventDispatcher: typeof import('svelte').createEventDispatcher
  const createForm: typeof import('@tanstack/svelte-form').createForm
  const createMutation: typeof import('@tanstack/svelte-query').createMutation
  const createQuery: typeof import('@tanstack/svelte-query').createQuery
  const derived: typeof import('svelte/store').derived
  const formatDate: typeof import('../lib/composables/currency').formatDate
  const formatIDR: typeof import('../lib/composables/currency').formatIDR
  const get: typeof import('svelte/store').get
  const getAllContexts: typeof import('svelte').getAllContexts
  const getContext: typeof import('svelte').getContext
  const hasContext: typeof import('svelte').hasContext
  const onDestroy: typeof import('svelte').onDestroy
  const onMount: typeof import('svelte').onMount
  const readable: typeof import('svelte/store').readable
  const setContext: typeof import('svelte').setContext
  const tick: typeof import('svelte').tick
  const useQueryClient: typeof import('@tanstack/svelte-query').useQueryClient
  const writable: typeof import('svelte/store').writable
}
