// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Badge: typeof import("./../lib/components/ui/badge/badge.svelte")["default"]
    const Button: typeof import("./../lib/components/ui/button/button.svelte")["default"]
    const DropdownAction: typeof import("./../lib/components/utils/DropdownAction.svelte")["default"]
    const Input: typeof import("./../lib/components/ui/input/input.svelte")["default"]
    const Label: typeof import("./../lib/components/ui/label/label.svelte")["default"]
    const Lucide: typeof import("./../lib/components/utils/Lucide.svelte")["default"]
    const Separator: typeof import("./../lib/components/ui/separator/separator.svelte")["default"]
    const SheetLayoutForm: typeof import("./../lib/components/utils/SheetLayoutForm.svelte")["default"]
    const Skeleton: typeof import("./../lib/components/ui/skeleton/skeleton.svelte")["default"]
    const Sonner: typeof import("./../lib/components/ui/sonner/sonner.svelte")["default"]
}

export {}
